import os

os.system("python generate_images_gaussian_noise2.py --image /Users/salvo/project_git/FinID/1_code/FinID-project-white-shark-master/data-augmentation/transformed_dataset/AN15131504/AN13141204.png --output /Users/salvo/project_git/FinID/1_code/FinID-project-white-shark-master/data-augmentation/transformed_dataset/AN15131504 --dir /Users/salvo/project_git/FinID/1_code/FinID-project-white-shark-master/data-augmentation/transformed_dataset/AN15131504 --total 2")

